### PR TITLE
Librato Link to new space and updated Logo

### PR DESCRIPTION
**Pull request by benarent**
Librato has recently launched public spaces. A new version of the old Bundler dashboard.  This PR has a link to the updates space and has updated the Librato Logo as per 2015 branding.

### CODE REVIEW

**Comment by niklibrato** [comment]
+1

**Comment by segiddins** [comment]
Less data is visible at once with that new dashboard :/

**Comment by benarent** [comment]
@segiddins Thansk for the feedback and all hard work on Bundler. I took a quick screenshot to compare, and the new space adds more charts per area. http://cl.ly/image/3d2l1X0z3s45   Or is there another issue? Happy to help. We're at 2nd and Market, we'll happily buy a coffee & beer in exchange for feedback.

**Comment by segiddins** [comment]
Ah, on my 27" monitor the new dashboard is still only 3 panes wide, versus 6 for the old one.

**Comment by benarent** [comment]
@segiddins Agh, Yes. Let me check up on this.

**Pull request closed without merging**
