### PR TITLE
Docker guide code formatting

### PR DESCRIPTION
**Pull request by indirect**
This fixes the code blocks in the Docker guide that Middleman didn't know how to format, because they were written in GitHub Markdown and Middleman uses regular Markdown.

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
It needs bumping ruby version on `.travis.yml` too.

**Comment by indirect** [comment]
Ahh crap, my bad. I’ll try to update it later today, or anyone else can feel free to take care of it if they have time!

**Comment by colby-swandale** [comment]
@bundlerbot r+

**Comment by colby-swandale** [comment]
@bundlerbot retry

**Pull request merged**
