### PR TITLE
Add `RochesterinNYC` to contributors/team page

### PR DESCRIPTION
**Pull request by RochesterinNYC**
Thanks so much for the opportunity y'all.

- There are also two commits on this PR updating stuff related to contributors (contributor count) and development/contributing links.

### CODE REVIEW

**Comment by segiddins** [comment]
👍🏻 feel free to merge and deploy! Welcome 👏🏻

**Comment by RochesterinNYC** [comment]
Thanks @segiddins! Is there documentation somewhere on how we currently deploy out bundler-site?

**Comment by indirect** [comment]
`rake deploy` builds the site, creates a new commit in bundler.github.io, and pushes

**Comment by indirect** [comment]
(At least it should, if I didn't mess anything up. 😬)

**Comment by RochesterinNYC** [comment]
Yup, `bin/rake deploy` worked successfully, thanks. Apologies for the triple commit on `bundler/bundler.github.io` though. The `with_clean_env` invokes specifying of github username and password which I didn't realize until the third attempt is actually username and an access token if your account has two-factor auth.

**Pull request merged**
