### PR TITLE
Add documentation for bundler 1.8

### PR DESCRIPTION
**Pull request by moeffju**
Also updates some missing options. I hope I haven’t missed
anything. This does not update examples that mention Ruby
1.9.x to something that is actually still supported, that
should be done sometime soon though, in a different PR.

### CODE REVIEW

**Comment by TimMoore** [comment]
Thank you!

**Comment by moeffju** [comment]
Specificially, I updated the `commands.haml` overview and synced the changes I saw in the CHANGELOG as well as the options and most descriptions mentioned in the `bundler` manpage/ronn files.

**Comment by moeffju** [comment]
I updated the PR to make it clearer what I changed from the v1.7 docs.

**Comment by moeffju** [comment]
Let me know if there is something that needs fixing before you can merge.

**Comment by TimMoore** [comment]
I swear when I looked at this diff yesterday, it had the changes to `Rakefile` and `config.rb`, but I don't see them now. Did they get accidentally rebased out or am I going crazy?

In any case... I can fix that up now. Thanks so much for this, it's a big help!

**Comment by TimMoore** [comment]
This is live on bundler.io now. Thanks again @moeffju!

**Comment by moeffju** [comment]
@TimMoore You’re right, I forgot about the files in the root and accidentally rebased over them. Thanks for fixing that :)

**Pull request merged**
