### PR TITLE
Localize Sharing Code Guide into Spanish

### PR DESCRIPTION
**Pull request by arbonap**
Thanks so much for the contribution!
To make reviewing this PR a bit easier, please fill out answers to the following questions.

### What was the end-user problem that led to this PR?

The problem was...
- There was a missing Spanish translation for the "Sharing your code" guide.

### What was your diagnosis of the problem?

My diagnosis was...
- There's a lot of missing translations for Bundler documentation

### What is your fix for the problem, implemented in this PR?

My fix...
- To localize "Sharing your code" into Spanish.
### Why did you choose this fix out of the possible options?

I chose this fix because...
- To spread the awesomeness of Bundler documentation to Spanish-speakers 👌🏼

### CODE REVIEW

**Comment by arbonap** [comment]
@bronzdoc I would love to get some feedback if you have some time 📝

**Comment by bronzdoc** [comment]
Done @arbonap :)

**Comment by arbonap** [comment]
✨ thank you @bronzdoc! pushed up your edits.

**Comment by bronzdoc** [comment]
LGTM 👍

**Comment by indirect** [comment]
@bundlerbot r+

**Pull request merged**
