### PR TITLE
Haml pre block indentation fix and add paragraph tags to blocks of text

### PR DESCRIPTION
**Pull request by rgb-one**
- Simple solution to haml adding indentation to `pre` blocks from markdown files. 

For an illustration of this, have a look at the code block on the "Report a bug" page on the bundler website. Every line after the first additional indentation. The solution above is mentioned here: http://stackoverflow.com/questions/16605840/multiline-code-block-in-markdown-adds-unwanted-tabs

- Add paragraph tags to block of text on index page

### CODE REVIEW

**Comment by segiddins** [comment]
@rgb-one have a screenshot for comparison?

**Comment by indirect** [comment]
:+1: the code looks good, a screenshot would make it easy to merge without having to run this PR on my local machine :)

**Comment by rgb-one** [comment]
You can actually see it on  http://bundler.io clicking "Report a bug" on the sidebar.

**Comment by indirect** [comment]
Cool! In that case, a screenshot with before/after showing the fix would be awesome.

**Comment by rgb-one** [comment]
Before `~`, every line after the first has unspecified indentation
before

After `~`
after

**Comment by indirect** [comment]
Perfect :+1: :ship:

**Pull request merged**
