### PR TITLE
[WIP] Add Ruby Togther CTA

### PR DESCRIPTION
**Pull request by mrb**
Adds Ruby Together CTA to footer of bundler.io. /c @indirect 

screenshot 2016-11-07 12 36 18

### CODE REVIEW

**Comment by mrb** [comment]
Looks like it might need some more padding above the footer on e.g. https://bundler-site-staging-pr-274.herokuapp.com/docs.html

**Comment by sailorhg** [comment]
this is a great idea! let me make some design tweaks

**Comment by mrb** [comment]
@sailorhg :+1: Thanks!

**Comment by lynnco** [comment]
This supercedes https://github.com/bundler/bundler-site/pull/244 as the resolution for https://github.com/bundler/bundler-site/issues/219 !

**Comment by segiddins** [comment]
@lynnco to automatically close the issue, you should put that in the PR description, rather than a comment

**Comment by lynnco** [comment]
@segiddins I am aware. It is my personal opinion that it is rude to edit someone's PR description, rather than let them do it themselves.

**Comment by mrb** [comment]
@sailorhg Ping on this 😄

**Comment by indirect** [comment]
Closing for now, but hopefully we will have a redone sponsors page soonish, and we can then adapt a CTA based on that.

**Pull request closed without merging**
