### PR TITLE
Update to ruby 2.4

### PR DESCRIPTION
**Pull request by tejasbubane**
Ruby version was [downgraded](https://github.com/bundler/bundler-site/commit/61ac8c6694fb3dba96a67e620d7fea0fe09f0f84) since middleman did not support ruby 2.4, but [now it does!](https://github.com/middleman/middleman/pull/2038).

Following gem updates were required:

* middleman to version `4.2` and rubyracer to `0.12.3` for this to work.
* `builder`, `rake` and `sprockets` to their respective latest versions to remove Fixnum warnings.

### CODE REVIEW

**Comment by segiddins** [comment]
Thanks!

@bundlerbot r+

**Comment by tejasbubane** [comment]
I am getting these warnings from middleman:

```
Haml::TempleEngine: Option :locale is invalid
Haml::TempleEngine: Option :outvar is invalid
Haml::TempleEngine: Option :context is invalid
```

There is an open issue for this: https://github.com/middleman/middleman/issues/2087.

**Comment by segiddins** [comment]
Can you please downgrade back to the version of HAML we were using before?

**Comment by tejasbubane** [comment]
@segiddins I downgraded the haml version to what was before `4.0.7`.

**Comment by segiddins** [comment]
@bundlerbot r+

**Pull request merged**
