### PR TITLE
September Monthly Update

### PR DESCRIPTION
**Pull request by rubymorillo**
Blog post with September monthly update information

### CODE REVIEW

**Comment by indirect** [comment]
thanks!

@bundlerbot r+

**Comment by indirect** [comment]
hmmm.... maybe bors isn’t configured right here yet?

@bundlerbot retry

**Comment by segiddins** [comment]
@indirect might need to update the Travis config?

**Comment by notriddle** [comment]
```
branches:
  only:
    - master
    - auto
```

**Comment by colby-swandale** [comment]
@bundlerbot r+

**Comment by colby-swandale** [comment]
@bundlerbot r+

**Comment by colby-swandale** [comment]
@bundlerbot r+

**Pull request merged**
