### PR TITLE
Docs(gems-from-git page): Fix incorrect URLs for nokogiri

### PR DESCRIPTION
**Pull request by RDIL**
### What was the end-user problem that led to this PR?

The problem was that this example was pointing nokogiri to rack, pretty sure that's not right.

### What is your fix for the problem, implemented in this PR?

The URLs have been updated.  

### Why did you choose this fix out of the possible options?

Seemed most logical

### CODE REVIEW

**Comment by esasse** [comment]
@bundler/bundlerbot r+

**Comment by RDIL** [comment]
What's that do?

**Comment by esasse** [comment]
@bundlerbot r+

**Comment by esasse** [comment]
Thanks @RDIL !

**Pull request merged**
