### PR TITLE
[WIP] Anchored titles in content.

### PR DESCRIPTION
**Pull request by simi**
Hello!

It will be nice to get content titles linkable via anchors. I prepared a small demo. Can anyone confirm this is good idea? I would like to finish it after.

screenshot-localhost 4567 2014-12-26 09-23-03

:christmas_tree:

### CODE REVIEW

**Comment by simi** [comment]
Hello and happy new year!
FYI I'm finishing this. But I'm wondering if all haml files are maintained manually. Isn't there any process how to generate some of those files? For example `source/v1.7/bundle_binstubs.haml` looks like generated file.

Also I will probably need to remove current id parameter for various h2 tags ([example](https://github.com/bundler/bundler-site/blob/master/source/v1.7/bundler_sharing.haml#L1-L2)). I can't find reason for them anyway.

**Comment by TimMoore** [comment]
AFAIK they are maintained by hand.

**Comment by indirect** [comment]
@simi any progress on this? if possible, it would be great to keep the existing anchors, but I understand if that isn't possible. Thanks!

**Comment by simi** [comment]
I'm thinking how to automate this to avoid manual maintenance.

**Comment by moeffju** [comment]
@simi How about adding the anchors manually (or semi-automatically through editor features) for v1.7 and v1.8 while you look to fully automate this?

**Comment by kruczjak** [comment]
It should be done in #218 :)

**Pull request closed without merging**
