### PR TITLE
tiny bit of instructions to clarify system requirements

### LINKED ISSUE #256: Note that the install instructions assume a valid Ruby and RubyGems installation
So that OS X users / etc reading the [index page](https://github.com/bundler/bundler-site/blob/master/source/v1.13/index.html.haml) know that they may require extra steps

### PR DESCRIPTION
**Pull request by feministy**
closes #256

Just a quick note to clarify system requirements! I didn't link to any install guides since bundler is used by so many different operating systems.

Bonus ✨ change: I removed a line break that was making the `:code` formatting have an extra line break (I couldn't not see it omg 😳)

### CODE REVIEW

**Comment by colby-swandale** [comment]
I think it would be a huge benefit for anyone that hasn't not used Ruby/RubyGems/Bundler before that we link to somewhere that shows how to install Ruby-lang/RubyGems. Maybe the Ruby-lang homepage would be fine. https://www.ruby-lang.org

**Comment by feministy** [comment]
Good idea! I'll link to RubyGems and Ruby 👍

**Comment by hmistry** [comment]
@colby-swandale after our conversation today, I had a thought that there was no mention of any prerequisites on our page - this can be one way to ensure a user is ready for bundler and has encountered what a gem is.

**Comment by indirect** [comment]
@bundlerbot r+

**Pull request merged**
